import { FineShape } from '@/types/fineshape/FineShape';

export const initialBlankFineShapeState: FineShape = {
    id: undefined,
    todayDate: undefined,
    userCep: undefined,
    userCity: undefined,
    userState: undefined,
    userAddress: undefined,
    userEthnicity: undefined,
    userAddressComplement: undefined,
    isPhoneWhatsapp: undefined,
    name: undefined,
    phone: undefined,
    birthdate: undefined,
    gender: undefined,
    userCpf: undefined,
    userWeight: undefined,
    userHeight: undefined,
    email: undefined,
    userAge: undefined,
    userWaist: undefined,
    userBelly: undefined,
    userChest: undefined,
    userImc: undefined,
    userFatPercentage: undefined,
    userMusclePercentage: undefined,
    userVisceralFatPercentage: undefined,
    userBodyAge: undefined,
    userRM: undefined,
    coachId: undefined,
};
