import { RouteNames } from '@/routes/routes_names';

export const navigationApps = [
  {
    id: 1,
    title: 'Comunidade',
    icon: 'camera',
    typeIcon: 'FontAwesome',
    color: '#90D692',
    size: 80,
    screen: 'Home',
  },
  {
    id: 2,
    title: 'Saúde',
    icon: 'heartbeat',
    typeIcon: 'FontAwesome',
    color: '#90D692',
    size: 80,
    screen: 'Home',
  },
  {
    id: 3,
    title: 'Treinos',
    icon: 'walking',
    typeIcon: 'FontAwesome5',
    color: '#90D692',
    size: 80,
    screen: 'Home',
  },
  {
    id: 4,
    title: 'Água',
    icon: 'water',
    typeIcon: 'Ionicons',
    color: '#90D692',
    size: 80,
    screen: 'Home',
  },
  {
    id: 5,
    title: 'Nutrição',
    icon: 'food-apple',
    typeIcon: 'MaterialCommunityIcons',
    color: '#90D692',
    size: 80,
    screen: RouteNames.logged.food.daily,
  },
  {
    id: 6,
    title: 'Métricas',
    icon: 'google-analytics',
    typeIcon: 'MaterialCommunityIcons',
    color: '#90D692',
    size: 80,
    screen: RouteNames.logged.food.details.initial,
  },
  {
    id: 7,
    title: 'Peso',
    icon: 'weight',
    typeIcon: 'FontAwesome5',
    color: '#90D692',
    size: 80,
    screen: 'Home',
  },
  {
    id: 8,
    title: 'Medalhas',
    icon: 'medal-outline',
    typeIcon: 'MaterialCommunityIcons',
    color: '#90D692',
    size: 80,
    screen: 'Home',
  },
  {
    id: 9,
    title: 'Sono',
    icon: 'sleep',
    typeIcon: 'MaterialCommunityIcons',
    color: '#90D692',
    size: 80,
    screen: 'Home',
  },
];
