export const TopicsApps = [
    {
        id: 1,
        title: 'Nutrição',
        icon: 'food-apple',
        typeIcon: 'MaterialCommunityIcons',
        color: '#90D692',
        size: 80,
        screen: 'Home',
    },
    {
        id: 2,
        title: 'Orgânicos',
        icon: 'leaf',
        typeIcon: 'FontAwesome',
        color: '#90D692',
        size: 80,
        screen: 'Home',
    },
    {
        id: 3,
        title: 'Suplementos',
        icon: 'superscript',
        typeIcon: 'FontAwesome',
        color: '#90D692',
        size: 80,
        screen: 'Home',
    },
    {
        id: 4,
        title: 'Sono',
        icon: 'bed',
        typeIcon: 'FontAwesome',
        color: '#90D692',
        size: 80,
        screen: 'Home',
    },
];
