const RoutesUnlogged = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    SPLASH: 'SPLASH',
    SINGUP: 'SINGUP',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    SINGUP_GOALS: 'SINGUP_GOALS',
    SINGUP_NUTRIENTS: 'SINGUP_NUTRIENTS',
    SINGUP_SIZES: 'SINGUP_SIZES',
}
export default RoutesUnlogged;